### ISSUE TITLE
bug:  can not login in google's project idx (dart-shelf API server project)

### ISSUE THREAD

**Issue by jayjayesh** [invertase/globe#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.0.12

### Project ID

N/A

### Description

Can not login on Google's Project IDX ( Dart-Server-App ) template

### Steps to reproduce

1. Go to Googles Project IDX web portal : https://idx.google.com
2. create new  dart project  description ( Build API server with dart ).
3. it will automatically build and run, just to confirm everything is working fine.
4. open terminal.
5. install globe cli  ( it was version 0.0.12 ).
6. globe login : it will show you link but that link not working, when click on it, it say (Not found.) on webpage.

### Expected behavior

login link should work properly

### Screenshots

![Screenshot 2024-09-26 at 8 21 26 PM](https://github.com/user-attachments/assets/c038fc7d-ec38-4e81-9472-0f87f2b70f86)

**Comment by kaziwaseef** [comment]
Hi, thanks for reporting this. On an initial look, it looks like an issue with logging into Globe from the idx environment. I will take a look into it to figure out if we can support this environment.

For situations such as this, we have a token based workflow. You can create access tokens from your Globe dashboard > Settings > Access Tokens.

You also need the project id for the project you want to deploy to from Project > Settings > Scroll Down to Project Id

Then you can run:
```
globe deploy --project <your_project_id_from_dashboard> --token <your_access_token>
```

Try this workaround as we look into it.

**Comment by jayjayesh** [comment]
@kaziwaseef thanks for quick update, I have followed your steps and it worked,
here is steps that I have perform to make it work on project Idx. 

```
(1) add your github project to their portal [Globe dashboard](https://globe.dev).
(2) while adding your github project, make sure you change entrypoint : by default it was (lib/main) but I have to change it to (bin/server.dart) for this project.
(2) get project_id : Globe dashboard > Project > Settings > Scroll Down to Project Id.
(3) generate token : Globe dashboard > Settings > Access Tokens.
(4) run this command into project idx terminal : globe deploy --project <your_project_id_from_dashboard> --token <your_access_token>
```

**Comment by kaziwaseef** [comment]
Thanks for confirming. We will work on improving the process for using Globe with browser based IDE's.
