### ISSUE TITLE
bug:  Globe Discord Link Expired

### ISSUE THREAD

**Issue by khanjasir90** [invertase/globe#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

N/A

### Project ID

N/A

### Description

Globe Discord Community Link in Readme file has expired, need to replace it with new one.

### Steps to reproduce

Click on discord icon in read me file.

### Expected behavior

After clicking on discord icon in readme file, it should open an active discord invite link.

**Comment by khanjasir90** [comment]
@Salakar can you please provide me with new link so I can update the same.

Thanks,

**Comment by khanjasir90** [comment]
<img width="633" alt="Screenshot 2024-10-07 at 9 25 45 PM" src="https://github.com/user-attachments/assets/323f89e7-05dd-491c-890e-a1621f11773d">

Hey @kaziwaseef not working for me

**Comment by IldySilva** [comment]
not working for me
![image](https://github.com/user-attachments/assets/91eaaaf2-ec70-4f7b-bc12-6dd3905b01a1)
