### ISSUE TITLE
bug:  This site can’t be reached ( after success deployment)

### ISSUE THREAD

**Issue by kalismeras61** [invertase/globe#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.0.12

### Project ID

865fbf92-3b46-402d-a662-a4620eb09260

### Description

I don't have any issue but i can't access website!

https://heatmap-analytics-server-uv9gf1c-yasin-ilhan-futurist-programmer.globeapp.dev 

### Steps to reproduce

Go to webpage you will see issue

https://heatmap-analytics-server-uv9gf1c-yasin-ilhan-futurist-programmer.globeapp.dev

### Expected behavior

Must show server response

### Screenshots

no need

### Additional context and comments

no need

**Comment by codekeyz** [comment]
@kalismeras61 As a temporal solution, could use a shorter project name? There seems to be a weird issue with DNS resolution on our side.

**Comment by kalismeras61** [comment]
Yes, i thought same think, after changing organisation name it is working now. Thanks

**Comment by codekeyz** [comment]
Woohoo 👍🏾 , nice @kalismeras61

**Comment by kalismeras61** [comment]
Closing now, but needs to be fix for long url.
