### ISSUE TITLE
bug:  Dart Frog tutorial Counter can't work on Globe

### ISSUE THREAD

**Issue by plumsky** [invertase/globe#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

N/A

### Project ID

c7804b97-476e-4cf5-9b69-6c85b43d0f61

### Description

Variables in the middleware are reinitialized after a period of time(1~2 m).

### Steps to reproduce

Open web https://control-center.globeapp.dev/count

### Expected behavior

Requested this route time(s) will not to be reset, unless server reset.

**Comment by codekeyz** [comment]
@plumsky How are you persisting state in your backend?

**Comment by plumsky** [comment]
@codekeyz Well, just like in https://dartfrog.vgv.dev/docs/tutorials/counter
Code is below:
```
import 'package:dart_frog/dart_frog.dart';

int _count = 0;

Handler middleware(Handler handler) {
  return handler.use(provider<int>((_) => ++_count));
}
```

**Comment by codekeyz** [comment]
@plumsky You can refer to our Architecture Document for more details. -> https://docs.globe.dev/infrastructure#architecture

**Comment by plumsky** [comment]
@codekeyz Ok, thx I will check about it.
