### ISSUE TITLE
request:  Auto Re-Deploy when there is new update from github repository

### ISSUE THREAD

**Issue by indratrisnar** [invertase/globe#119]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

As a dart developer, i wanto globe be able to auto deploy when i update my repo in github. or specified update deploy from globe cli

### Reasoning

as for me, this will usefull when there is new deploy update oftenly.

**Comment by kaziwaseef** [comment]
Hello. If I am understanding correctly, you would like to create deployments based on commits you push to your Github repository.

If so, then this is something we already support: 
- [Connect Github to an existing project](https://docs.globe.dev/deployments/github-integration#connecting-to-an-existing-project)
- [Overall documentation on Github integration](https://docs.globe.dev/deployments/github-integration)

Please let me know if this is what you were looking for.

**Comment by indratrisnar** [comment]
Thank you, now work

Pada Sen, 2 Des 2024 16.08, Kazi Waseef ***@***.***> menulis:
