### ISSUE TITLE
[request]   Add Support Dart Framework ALFRED

### ISSUE THREAD

**Issue by gwcangtip** [invertase/globe#14]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

as a developer who is used to using node js express as an api, now I moved to dart and I found a framework that is similar to express in dart

here he is 

[ALFRED](https://pub.dev/packages/alfred) A performant, expressjs like web server / rest api framework thats easy to use and has all the bits in one place

### Reasoning

Of all the frameworks, Alfred is the easiest because the syntax is similar to Express JS

### Additional context and comments

I hope you can support this framework in the world, thank you

**Comment by kaziwaseef** [comment]
Hello @gwcangtip, based on what I read, Alfred projects should work already except `Directory` responses for static files. 

I have tested the basic example and it is working: https://alfred-simple-vryzlhz-waseef.globeapp.dev/example

For this code: 
```dart
import 'dart:io';

import 'package:alfred/alfred.dart';

void main() async {
  final app = Alfred();

  app.get('/example', (req, res) => 'Hello world');

  await app.listen(
    int.tryParse(Platform.environment['PORT'] ?? '8080') ?? 8080,
  );
}
```

Please do set Port with `Platform.environment['PORT']` as this enables globe to assign the port as needed.

Please let us know if parts of it are not working as expected or if you find any other issues with this. Closing this issue, but feel free to reopen if you believe that additional discussion needs to be done.

 Thanks.
