### ISSUE TITLE
bug:  Cannot Sign In to Globe

### ISSUE THREAD

**Issue by indratrisnar** [invertase/globe#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.0.7

### Project ID

none

### Description

i cannot sign in to globe.

condition:
- check internet connection: Good
- check globe CLI: Good
- project: ready to deploy (with/without) github

### Steps to reproduce

step:
- login via google, choose account google, loading, but then redirect to login page again
- login via CLI, choose account github, loading, but then redirect to login page again

### Expected behavior

login successfully

**Comment by indratrisnar** [comment]
also "Send me a magic link" not work

**Comment by Ehesp** [comment]
Can you share your email address (feel free to ping on Discord).

>  also "Send me a magic link" not work

Not work in what way?

**Comment by indratrisnar** [comment]
I use this email to sign in
***@***.***

Send magic link not work (none reply or anything send from globe to my
email)

Pada Kam, 15 Feb 2024 23.30, Elliot Hesp ***@***.***> menulis:

**Comment by indratrisnar** [comment]
now globe fixed, i can sign in
