### ISSUE TITLE
request:  Make it possible to delete a project 

### ISSUE THREAD

**Issue by indratrisnar** [invertase/globe#43]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

i want delete my globe project, but there are no action to delete project.
<img width="934" alt="Screenshot_1" src="https://github.com/invertase/globe/assets/65453071/a8212526-3f5a-4f50-8558-5453abe55d1f">

### Reasoning

the project no need again

**Comment by kaziwaseef** [comment]
Hello. Sorry, this feature is currently not supported by globe. However, we have it in our plan for the future.

**Comment by stMerlHin** [comment]
Please @kaziwaseef  can you provide a link to this roadmap ?

**Comment by codekeyz** [comment]
This features has been implemented @indratrisnar. Please refer to this blog post https://globe.dev/blog/deleting-projects/
