### ISSUE TITLE
bug:  Deploy via CLI always failed

### ISSUE THREAD

**Issue by indratrisnar** [invertase/globe#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.0.7

### Project ID

886cd2a0-5e5c-480d-b3bc-8438aabcc7ea

### Description

when `globe deploy --prod` always failed.  i have tried 2 times fro different project. but if i use github to deploy (success).

### Steps to reproduce

- globe login
- globe deploy --prod
- fill project info
- Deployment failed

### Expected behavior

Deployed (deploy success)

### Screenshots

![image](https://github.com/invertase/globe/assets/65453071/6efc7d2f-9974-46af-b702-fd192e91bd7f)

### Additional context and comments

`globe build-logs --deployment="a791305e-45df-4290-b09b-82d37350fdd3"`

![image](https://github.com/invertase/globe/assets/65453071/7dc70632-abe1-444e-9d6e-84468a861cc9)

**Comment by indratrisnar** [comment]
when i use deploy from github == success

![image](https://github.com/invertase/globe/assets/65453071/533357ed-6ae1-4577-a61b-f6450dffc952)

**Comment by Ehesp** [comment]
Build logs via CLI should be working now which should identify the issue.

**Comment by lesnitsky** [comment]
@indratrisnar could you please try to deploy via CLI on the latest version?
Run `globe update` before deploying.

**Comment by indratrisnar** [comment]
I have updated globe cli, with `globe update`
then I tried re-deploying production, success.

but I haven't tried deploying it from scratch again

**Comment by Ehesp** [comment]
Great thanks for confirming - I'll close for now, please let me know if you run into anymore issues.
