### ISSUE TITLE
bug:  Build logs don't show

### ISSUE THREAD

**Issue by fior-di-latte** [invertase/globe#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

v0.0.8

### Project ID

59273fa3-e34f-4684-9ad4-bc98ea7c5cf3

### Description

The build 
`flutter build web --release --no-tree-shake-icons --web-renderer canvaskit`
with target  `lib/main_development.dart
` is failing.

I would like to see the build logs, but  `globe build-logs --deployment="59273fa3-e34f-4684-9ad4-bc98ea7c5cf3"` does not return anything. The Globe GUI is also stuck in a loading state.

### Steps to reproduce

See above

### Expected behavior

I expect to see building logs.

### Screenshots

<img width="816" alt="image" src="https://github.com/invertase/globe/assets/30835670/78c1dc2a-8610-44aa-9228-72745160eb76">

**Comment by Ehesp** [comment]
This should now be fixed - please give it a try and let me know. Thanks

**Comment by fior-di-latte** [comment]
Yes, the problem is resolved. Thanks 👍
