### ISSUE TITLE
bug:  Deactivate build_runner problems

### ISSUE THREAD

**Issue by fior-di-latte** [invertase/globe#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

v0.0.9

### Project ID

1407ad6f-1151-41ad-8870-9feaa00a292a

### Description

When build_runner is deactivated in the Settings, 
the build_runner apparently still runs. The build fails with the following log:
```
Starting BUILD_RUNNER
FormatException: Package
❌ BUILD_RUNNER
🏁 BUILD_RUNNER took 14ms
```

### Steps to reproduce

1. Deactivate a build_runner and watch it still being triggered

### Expected behavior

I do not expect the build_runner to run.

### Screenshots

<img width="831" alt="image" src="https://github.com/invertase/globe/assets/30835670/2fb26b69-b065-4058-9320-22b62440884d">

**Comment by hhayak** [comment]
I have the same issue. I think build_runner (and probably the other options) is overriden by the "Framework preset", which is Flutter in my case.

**Comment by Ehesp** [comment]
Hmm, do you have any dependencies which require build runner?

I'll also check the settings are being applied correctly on your project
