### ISSUE TITLE
request:  Add support for having access to Environment Variables during build_runner phase

### ISSUE THREAD

**Issue by kaziwaseef** [invertase/globe#59]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

As a developer, I want to be able to set values of the environment variables in a class for better type safety. Packages currently exist such as `envied` that does this using build_runner.

### Reasoning

If the environment variables were avail during build_runner stage, then they can be set into a generated class and we can ensure type safety for environment variables, and have `Platform.environment` work in prod and `.env` file locally.

### Additional context and comments

Update documentation.

**Comment by codekeyz** [comment]
This should be resolved now. Closing...
