### ISSUE TITLE
globe deploy should respect .gitignore

### ISSUE THREAD

**Issue by lesnitsky** [invertase/globe#6]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Respect `.gitignore` when deploying via Globe CLI.

### Reasoning

[This](https://github.com/invertase/globe/blob/e025aaf35ecf168de569483c1e992a17ff012fbc/packages/globe_cli/lib/src/commands/deploy_command.dart#L56) suggests the whole directory is uploaded when deploying via Globe CLI. It makes sense to respect `.gitignore` to avoid any inconsistencies between CLI deployments and GitHub integration.

**Comment by Salakar** [comment]
The zipDir method handles gitignore parsing & removal: https://github.com/invertase/globe/blob/main/packages/globe_cli/lib/src/utils/archiver.dart#L12-L45
