### ISSUE TITLE
request: Make it clear that the project should be re-deployed after settings/env vars are updated

### ISSUE THREAD

**Issue by lesnitsky** [invertase/globe#61]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

I'd like to have a button that says "Re-deploy" if I update settings/env vars.

### Reasoning

There's a bit of confusion about env vars and it's not clear that the project should be deployed again in order to new env vars be available for the deployment

### Additional context and comments

Discord discussion: https://discord.com/channels/1179425190007021568/1214890391250145290

**Comment by suragch** [comment]
Another option to make a smooth UX could be to scan the GitHub repo that is being imported. If it contains a `Platform.environment` reference, then prompt the user to enter the key-value pair(s) and defer deployment until after those have been entered. Both times I imported projects from GitHub I assumed that whatever key-value pairs I entered here would be included in the deployment:


<img width="898" alt="Screenshot 2024-03-06 at 11 23 33" src="https://github.com/invertase/globe/assets/10300220/f33d0d3c-0ee5-45c4-ae18-14bd142f9b9c">

**Comment by codekeyz** [comment]
Blocked by https://invertase.slack.com/archives/C058UFSKVSP/p1711445443342939

**Comment by lesnitsky** [comment]
Needs figuring out better UI
