### ISSUE TITLE
bug: Redirect loop detected when running globe deploy

### ISSUE THREAD

**Issue by bizz84** [invertase/globe#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.0.9+3

### Project ID

2f660d10-2f92-43d4-b000-7ff186b7f06c

### Description

I created a Dart shelf app and when I try to deploy it with the CLI I get this error:

```
globe deploy --verbose
Verbose logging enabled.
❓ Link this project to Globe "/Users/andrea/work/codewithandrea/github/flutter/openai_dart_shelf_flutte
❓ Link this project to Globe "/Users/andrea/work/codewithandrea/github/flutter/openai_dart_shelf_flutter/shelf_backend"? (Y/n) Yes
Fetching user organizations
API Request: GET /user/orgs
Redirect loop detected
```

### Steps to reproduce

Follow these steps:

```bash
git clone https://github.com/bizz84/openai_dart_shelf_flutter
cd openai_dart_shelf_flutter/shelf_backend
globe deploy --verbose
```

### Expected behavior

The deployment should be completed successfully.

Instead, I get a `Redirect loop detected` error.

**Comment by Ehesp** [comment]
Thanks, will investigate. Not seen this one before.

**Comment by t-kietzmann** [comment]
I've currently the same error when deploying project be8e60eb-6125-4368-8666-aef739cda872 from the CLI.
The last deployment is over 2 month ago and worked well.

**Comment by t-kietzmann** [comment]
I have now reinstalled the Globe CLI and it works again

**Comment by komiljonovshohjahon** [comment]
Also had the same issue.
I logged in with another account a long time ago.
And recently activated Globe again and tried to log in with another account. Says already logged in(I thought logged in as my new email).
But was giving me a _redirect-detected_ loop.
I have fixed it by simply **logging out** and **logging in** again.

**Comment by codekeyz** [comment]
Going to close this issue now.
