### ISSUE TITLE
bug:  Breaking links in docs 

### ISSUE THREAD

**Issue by nikkieke** [invertase/globe#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

N/A

### Project ID

N/A

### Description

Some of the links in the getting-started folder, located within the docs folder, are broken. Clicking on these links results in a 404 error page. I have attached screenshots for clarity.

### Steps to reproduce

To reproduce the bug, navigate to the `/docs/getting-started/` directory and open any of the files. For example, if you choose the index.mdx file, you will notice that the links for "Backend Shelf Server" and "Frontend Flutter Web Application" are broken.

### Expected behavior

The links should work as expected when clicked.

### Screenshots

<img width="1156" alt="Screenshot 2024-04-02 024450" src="https://github.com/invertase/globe/assets/95222620/06fb8556-5ab8-45a0-b5ba-6ae73ecefc3a">

### Additional context and comments

I would appreciate being assigned to this issue.

**Comment by codekeyz** [comment]
Hey @nikkieke, I just verified these two links. They're working fine. 

- https://docs.globe.dev/getting-started/shelf-server
- https://docs.globe.dev/getting-started/flutter-web

Or are you referring to something else?

**Comment by nikkieke** [comment]
> Hey @nikkieke, I just verified these two links. They're working fine.
> 
> * https://docs.globe.dev/getting-started/shelf-server
> * https://docs.globe.dev/getting-started/flutter-web
> 
> Or are you referring to something else?

I tested it from the Github repo directly, I went through the docs folder and that's when I noticed the error. Although I just confirmed that on [https://docs.globe.dev/](docs.globe.dev) it's working fine.
