### ISSUE TITLE
request:  Support Vania WebServer

### ISSUE THREAD

**Issue by Shreemanarjun** [invertase/globe#78]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

There is no support for [Vania.](https://github.com/vania-dart/framework)

### Reasoning

Vania have all the modern features available.

**Comment by lesnitsky** [comment]
I'm not sure what exactly is meant by "There is no support for Vania", because Vania has something on docs about how to deploy to Globe https://vdart.dev/docs/deploy/globe
