### ISSUE TITLE
bug:  Invalid argument(s): A directory corresponding to fileSystemPath "public" could not be found [dart_frog as sub-package]

### ISSUE THREAD

**Issue by Nikoro** [invertase/globe#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

v0.0.10

### Project ID

55aaee1f-fe1b-4016-a9b7-16c2c25b86da

### Description

I've got this project structure:

project
-backend
--public
-frontend
-shared

3 dart packages, where backend is package with dart_frog server

After deploying it successfully using:
```
globe deploy
```

I've got this error in globe logs:

`Invalid argument(s): A directory corresponding to fileSystemPath "public" could not be found`

I was able to reproduce it locally running:
```
project % dart backend/build/bin/server.dart
```

The issue is that this code is run from root directory `project`

When I run it like this:
```
project % cd backend && dart build/bin/server.dart
```

Everything works fine.

The issue is I cannot do setup this in Globe settings. Because I can only pass path to entrypoint and cannot execut custom run code.

### Steps to reproduce

I've got this project structure:

project
-backend
--public
-frontend
-shared

3 dart packages, where backend is package with dart_frog server

After deploying it successfully using:
```
globe deploy
```

I've got this error in globe logs:

`Invalid argument(s): A directory corresponding to fileSystemPath "public" could not be found`

I was able to reproduce it locally running:
```
project % dart backend/build/bin/server.dart
```

The issue is that this code is run from root directory `project`

When I run it like this:
```
project % cd backend && dart build/bin/server.dart
```

Everything works fine.

The issue is I cannot do setup this in Globe settings. Because I can only pass path to entrypoint and cannot execut custom run code.

### Expected behavior

After deploying it successfully using:
```
globe deploy
```

Ther should be no error.

### Screenshots

![image](https://github.com/invertase/globe/assets/12560977/23999f34-9c56-4b0b-9265-9f1146a575de)

![image](https://github.com/invertase/globe/assets/12560977/21fa7b5f-3cfc-4848-9b6b-019bdc50b886)

**Comment by lesnitsky** [comment]
duplicate #38
