### ISSUE TITLE
request:  Add support for gRPC

### ISSUE THREAD

**Issue by flutter-painter** [invertase/globe#86]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Is it compatible with grpc ?

### Reasoning

because grpc is cool

**Comment by lesnitsky** [comment]
Currently, Globe has a limitation for deployment requests to be handled in under 5 seconds, gRPC generally requires long-running connections. We have this on our internal roadmap, although can't give any estimations about when it will become available.

**Comment by flutter-painter** [comment]
OK, thanks voir quick and clear response
