### ISSUE TITLE
request:  Update dependencies to use Serverpod CLI 2.0.0 

### ISSUE THREAD

**Issue by abdullahalamodi** [invertase/globe#88]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

globe deploy should updated to run [dart pub global activate serverpod_cli 2.0.0] behind the scenes 

### Reasoning

fail to deploy projects created with serverpod_cli 2.0.0

**Comment by codekeyz** [comment]
@abdullahalamodi You can actually set your own version of `Serverpod CLI` in Project Build Settings.

![Screenshot 2024-05-31 at 10 33 43 AM](https://github.com/invertase/globe/assets/22515508/19ebe4c0-36fb-4408-ae23-9b9e87a4368c)

I'll close this issue. Feel free to re-open if any more issues with this.

**Comment by lesnitsky** [comment]
@codekeyz we should have meaningful defaults. Currently we have 2.0.0-alpha.1 as default, it's worth upgrading to 2.0.0 if it's officially out.

**Comment by ps6067966** [comment]
Yes, Serverpod mini is in stable. Please update dependency as per latest stable version. 2.0.0

**Comment by ps6067966** [comment]
Globe Deployment is Awesome.
