### ISSUE TITLE
bug:  I cant deploy anymore

### ISSUE THREAD

**Issue by kfiross** [invertase/globe#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.1.1

### Project ID

7cfeb187-c5fa-4788-b211-47c669ace4c5

### Description

I got an error
"FormatException: Project"

### Steps to reproduce

run "globe deploy --prod"

### Expected behavior

deployin the app

**Comment by Ehesp** [comment]
Hey, we had this comment on discord too. Looking into it

**Comment by lesnitsky** [comment]
The issue is now resolved.
